python ../run_glue.py \
	--model_name_or_path bert-base-cased \
	--task_name ESNLI \
	--do_train \
	--do_eval \
	--data_dir ./esnli_train_dev_empty_expl/ \
	--max_seq_length 128 \
	--per_device_train_batch_size 32 \
	--learning_rate 2e-5 \
	--num_train_epochs 5.0 \
	--output_dir ./save_best_model/esnli_phe_emptyexpl_outputs/ \
	--overwrite_output_dir \
	--overwrite_cache \
	--esnli_input_type p+h:a,expl1:b \
	--save_best_model
